/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectaccount;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Dr.Stanley
 */
public class transfer extends javax.swing.JFrame {

    /**
     * Creates new form transfer
     */
    Connection con;
    ResultSet res;
    String rs;
    int curRow = 0;
    Statement Sobj;
    String passwd;
    double ball;

    public void ConnectionMth() {

        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/base1", "base1", "base1");
            Sobj = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            //String SQL= "select * from TABLE1";
            //res=Sobj.executeQuery(SQL);
            //res.next(); 
            amott.setEnabled(false);
            number.setEnabled(false);
            combo.setEnabled(false);
            Tb.setEnabled(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(transfer.this, e.getMessage());
        }
    }

    public transfer() {
        initComponents();
        ConnectionMth();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pwd = new javax.swing.JPasswordField();
        submit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Tb = new javax.swing.JButton();
        amott = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        number = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Transfering"));

        jLabel6.setText("Password");

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Transfer To", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        Tb.setText("Transfer");
        Tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TbActionPerformed(evt);
            }
        });

        jLabel2.setText("Amount");

        jLabel1.setText("Account number");

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TABLE1", "FirstBank", "AccessBank", "UBA", "ZenithBank" }));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });

        jLabel7.setText("Bank");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combo, javax.swing.GroupLayout.Alignment.TRAILING, 0, 358, Short.MAX_VALUE)
                    .addComponent(amott)
                    .addComponent(number, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(Tb, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(amott, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Tb, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(42, 42, 42)
                                .addComponent(pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Sobj.close();
            res.close();
        } catch (Exception e) {
        }
        this.dispose();
        new Account().setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        String pass = pwd.getText();
        try {
            //con= DriverManager.getConnection("jdbc:derby://localhost:1527/base1","base1","base1");
            //Sobj=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
            String SQL = "select * from TABLE1 where password='" + pass + "'";
            res = Sobj.executeQuery(SQL);
            res.next();
            String pasd = res.getString("password");
            String accN = res.getString("accnum");
            if (accN.equals(res.getString("accnum"))) {
                JOptionPane.showMessageDialog(transfer.this, "Sign_in successfull !!!");

                submit.setEnabled(false);
                pwd.setEnabled(false);
                ball = res.getDouble("Ballance");
                // ball= res.getDouble("Ballance");
                amott.setEnabled(true);
                number.setEnabled(true);
                Tb.setEnabled(true);
                combo.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(transfer.this, "Incorrect data !!!");
            }

        } //}
        catch (Exception e) {
            JOptionPane.showMessageDialog(transfer.this, e.getMessage());
        }
    }//GEN-LAST:event_submitActionPerformed

    private void TbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TbActionPerformed
//JOptionPane.showMessageDialog(transfer.this,ball);
        String accnumber = number.getText();
        //String pass= pwd.getText();
        String ego = amott.getText();
        String bank = (String) combo.getSelectedItem();

        double cash = Integer.parseInt(ego);
        try {
            String name = res.getString("accname");
            String acc = res.getString("accnum");
            int depID = res.getInt("id");
            if (cash > ball) {
                new fund().setVisible(true);
                Sobj.close();
                res.close();
                this.dispose();
            } else {
                double total = ball - cash;
                res.updateDouble("ballance", total);
                res.updateRow();
                Calendar dat = new GregorianCalendar();
                int day = dat.get(Calendar.DAY_OF_MONTH);
                int year = dat.get(Calendar.YEAR);
                int mon = dat.get(Calendar.MONTH);
                int hour = dat.get(Calendar.HOUR_OF_DAY);
                int min = dat.get(Calendar.MINUTE);
                mon++;
                String date = day + "-" + mon + "-" + year + " : " + hour + ":" + min;
                String detal1 = "***Transfer Reciept***\n" + "Name: " + name + "\nAccount number: " + acc + "\nAmount :"
                        + ego + "\n Transfered To:\n" + "Account number: " + accnumber + "\nBank: " + bank + "\n Date: " + date;

                // inserting into decription table 
                String SQLi = "select * from descrip";
                res = Sobj.executeQuery(SQLi);
                res.next();
                int id_det;

                if (res.last()) {
                    id_det = res.getInt("id_det");
                    id_det++;
                } else {
                    id_det = 1;
                }
                res.moveToInsertRow();
                res.updateString("description", detal1);
                res.updateInt("id_det", id_det);
                res.updateInt("identity_id", depID);
                res.updateInt("month", mon);
                res.updateString("date", date);
                res.insertRow();
//                 String detal1 = "Transfer Reciept\n" + "Name: " + name + "\nAccount number: " + acc + "\nAmount :" + 
//                        ego + "\n Transfered To:\n" +"\nAccount number: "+accnumber+"\nBank: "+bank;
                JOptionPane.showMessageDialog(transfer.this, detal1);

                String SQL = "select * from " + bank + " where accountnum='" + accnumber + "'";
                System.out.println(SQL);
                res = Sobj.executeQuery(SQL);
                System.out.println(SQL + " 2");
                res.next();
                double tball = res.getDouble("ballance");
                String name2 = res.getString("accname");
                String acc2 = res.getString("accnum");
                int depID2 = res.getInt("id");
                System.out.println(depID2);
                tball = tball + cash;
                // JOptionPane.showMessageDialog(transfer.this,tball);
                res.updateDouble("ballance", tball);
                res.updateRow();
                String detal = "***Recieved Transfer By: ***\n" + "Name: " + name + "\nAccount number: " + acc + "\nAmount :"
                        + ego + "\n Reciever:\n" + "Account name: " + name2 + "\nAccount number: " + acc2 + "\nBank: " + bank + "\n Date: " + date;
                // JOptionPane.showMessageDialog(transfer.this, detal);

                // inserting into decription table 
                String SQLi2 = "select * from descrip";
                res = Sobj.executeQuery(SQLi2);
                res.next();
                int id_det2;

                if (res.last()) {
                    id_det2 = res.getInt("id_det");
                    id_det2++;
                } else {
                    id_det2 = 1;
                }
                res.moveToInsertRow();
                res.updateString("description", detal);
                res.updateInt("id_det", id_det2);
                res.updateInt("identity_id", depID2);
                res.updateInt("month", 2);
                res.updateString("date", date);
                res.insertRow();
                new query().setVisible(true);
                this.dispose();
                Sobj.close();
                res.close();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(transfer.this, e.getMessage());
        }
    }//GEN-LAST:event_TbActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Tb;
    private javax.swing.JTextField amott;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField number;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
